### ISSUE TITLE
inspectContainer fails with JsonSyntaxException

### ISSUE THREAD

**Issue by dstore-dbap** [shekhargulati/rx-docker-client#67]
using "inspectContainer(containerId)" gives me

com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 3798

column 3798 is beginning of the "volumes"-object of the json, but I don't see either in the json returned from server nor in your code why BEGIN_ARRAY is expected here... May you want to take a look into it or write a test on inspect with volumes bound to a container

docker endpoint versions:

 Version:      1.10.1
 API version:  1.22

**Comment by arjenp** [comment]
I am getting the same errors. I'm trying to make a work around but I'm not very advanced in stuff like this. Do you have any idea how to fix this error ?

**Comment by shekhargulati** [comment]
@arjenp @dstore-dbap This issue is fixed now. I will release the new version today.

**Comment by shekhargulati** [comment]
@arjenp @dstore-dbap I have released version 0.2.1 which contain fix for this issue.
