### ISSUE TITLE
construct a request from Docker API json instead of builder api

### ISSUE THREAD

**Issue by cinterloper** [shekhargulati/rx-docker-client#85]
Is there a way to pass a piece of json describing the container i would like to create, instead of using the builder api?

**Comment by shekhargulati** [comment]
@cinterloper this is currently not supported. Are you planning to use this library for some project? If yes, then I can add the support.

**Comment by cinterloper** [comment]
well, if this feature was present yes i would use it in my project. 

 - my project is a Vert.x program that launches a group of containers, and a group of JVM threads (Verticals), and provides some discovery and start up coordination for them.
rx-docker-client would be superior to the blocking client im currently using because its reactive and Vertx is framed around that model
 
however, my project is a launcher/foundation on which to build other projects, and it needs to be able to specify the containers launch information by configuration

**Comment by shekhargulati** [comment]
@cinterloper I have added support for json based requests. There are few new methods added in the API to help you use Docker API json request. These methods will be available in 0.2.2 version of the client. It will be available in Maven Central by tomorrow morning. Let me know if you face any issues.

`Observable<DockerContainerResponse> createContainerObs(String jsonRequest, String name)`

`DockerContainerResponse createContainer(String jsonRequest, String name)`

`Observable<DockerContainerResponse> createContainerObs(String jsonRequest)`

`DockerContainerResponse createContainer(String jsonRequest)`

**Comment by shekhargulati** [comment]
@cinterloper `0.2.2` version is now available in Maven Central.

**Comment by cinterloper** [comment]
wow awesome! ill try it out

**Comment by shekhargulati** [comment]
@cinterloper is it working for you?

**Comment by shekhargulati** [comment]
closing this. Please open if it didn't worked for you.
